### ISSUE TITLE
Reminder to update toolz and cloudpickle dependencies in next release

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/dask-feedstock#104]
In https://github.com/dask/dask/pull/5997 we updated to `toolz>=0.8.2` and `cloudpickle>=0.2.2`

**Comment by jakirkham** [comment]
Also [`cytoolz`]( https://github.com/conda-forge/dask-feedstock/blob/ed47e7f411547732d9228cb3d2ccd9199d91e3fb/recipe/meta.yaml#L24 )
