### ISSUE TITLE
Update bokeh dependency

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/dask-feedstock#105]
There was an issue in `bokeh=2.0.0` where the `asyncio` event loop was being overwritten on Windows with Python 3.8+. That issue has since been fixed upstream (xref bokeh/bokeh#9776) and should be included in the next `bokeh` release.

We should update our dependency here to be `bokeh >=1.0.0,!=2.0.0`

**Comment by jakirkham** [comment]
Thanks for tracking all of this stuff 😄
