### ISSUE TITLE
Missing optional packages

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/dask-feedstock#206]
Dask provides [several](https://github.com/dask/dask/blob/2022.10.2/setup.py#L14-L25) optional installs, and (in the absence of a better [mechanism](https://github.com/conda/conda/issues/7502) for dealing with optional dependencies) we should have a possibility for users to install those, e.g. `conda install dask-complete`, which appears in conda environment specs in the [wild](https://github.com/modin-project/modin/blob/0.17.0/environment-dev.yml#L8), but doesn't do what's expected.

**Comment by mrocklin** [comment]
Dask is the metapackage that you're looking for.  We use dask-core for just-dask.

**Comment by h-vetinari** [comment]
> Dask is the metapackage that you're looking for. We use dask-core for just-dask.

The problem is that this mapping is not at all obvious, and has holes for people who want to install a particular `dask[option]` (instead of getting everything). In other feedstocks I'm aware of with multiple optional installs, conda-forge can provide several outputs (spelled `dask-option`) so that users have a way to map their pip-requirements to conda.

> Closing as I believe that should fix the issue you're running into, but feel free to re-open if needed

Please reopen, I can't do it myself (not a maintainer on this feedstock).
