### ISSUE TITLE
Set `pandas >=1.3` and `numpy >=1.21`

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/dask-feedstock#214]
In https://github.com/dask/dask/pull/9950 we bumped our minimum versions `numpy` and `pandas` to `pandas >=1.3` and `numpy >=1.21`. This is just a reminder to do the same here when we push out the next release. 

cc @jakirkham

**Comment by jakirkham** [comment]
cc @fjetter

**Comment by jakirkham** [comment]
cc @charlesbluca
