### ISSUE TITLE
Large number of dependencies

### ISSUE THREAD

**Issue by rth** [conda-forge/dask-feedstock#22]
The latest version of dask  (0.15.1) on conda forge pulls around 37 dependency packages for a new install. While even the version 0.15.0 on the main conda channel pulls 29 packages (see results below). For comparison installing numpy, scipy, pandas and scikit-learn have a dependency tree of only 19 packages.

Because of this, as a package maintainer, I am quite hesitant to add the latest dask conda package to my list of dependencies. I am aware than when installing with `pip` all of these dependencies don't get installed and are [marked as optional](https://github.com/dask/dask/blob/master/setup.py#L9). Could something be done about this in the conda package as well,
 - either by marking some dependencies as optional (it seems to be possible with latest conda versions https://github.com/conda/conda/pull/4982)
 - or by creating a separate conda-forge package with the bare minimum of dependencies (excluding bokeh etc).?

Thank you!

***Dependencies for dask 0.15.1 (PY3.6, Linux) from conda-forge***
```
conda create --dry-run -n dummy dask=0.15.1=py36_0
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/rth/miniconda3/envs/dummy:

The following NEW packages will be INSTALLED:   

    bkcharts:         0.2-py36_0
    bokeh:            0.12.6-py36_0
    click:            6.7-py36_0
    cloudpickle:      0.2.2-py36_0
    dask:             0.15.1-py36_0 conda-forge 
    distributed:      1.17.1-py36_0
    heapdict:         1.0.0-py36_1
    jinja2:           2.9.6-py36_0
    locket:           0.2.0-py36_1
    markupsafe:       0.23-py36_2
    mkl:              2017.0.3-0
    msgpack-python:   0.4.8-py36_0
    numpy:            1.13.1-py36_0
    openssl:          1.0.2l-0
    pandas:           0.20.3-py36_0
    partd:            0.3.8-py36_0
    pip:              9.0.1-py36_1
    psutil:           5.2.2-py36_0
    python:           3.6.2-0
    python-dateutil:  2.6.1-py36_0
    pytz:             2017.2-py36_0
    pyyaml:           3.12-py36_0
    readline:         6.2-2
    requests:         2.14.2-py36_0
    setuptools:       27.2.0-py36_0
    six:              1.10.0-py36_0
    sortedcontainers: 1.5.7-py36_0
    sqlite:           3.13.0-0
    tblib:            1.3.2-py36_0
    tk:               8.5.18-0
    toolz:            0.8.2-py36_0
    tornado:          4.5.1-py36_0
    wheel:            0.29.0-py36_0
    xz:               5.2.2-1
    yaml:             0.1.6-0
    zict:             0.1.2-py36_0
    zlib:             1.2.8-3

```
***Dependencies for dask 0.15.0 (PY3.6, Linux) from main channel***
```

conda create --dry-run -n dummy dask=0.15.0=py36_0
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/rth/miniconda3/envs/dummy:

The following NEW packages will be INSTALLED:

    bkcharts:        0.2-py36_0   
    bokeh:           0.12.6-py36_0
    cloudpickle:     0.2.2-py36_0 
    dask:            0.15.0-py36_0
    jinja2:          2.9.6-py36_0 
    locket:          0.2.0-py36_1 
    markupsafe:      0.23-py36_2  
    mkl:             2017.0.3-0   
    numpy:           1.13.1-py36_0
    openssl:         1.0.2l-0     
    pandas:          0.20.3-py36_0
    partd:           0.3.8-py36_0 
    pip:             9.0.1-py36_1 
    python:          3.6.2-0      
    python-dateutil: 2.6.1-py36_0 
    pytz:            2017.2-py36_0
    pyyaml:          3.12-py36_0  
    readline:        6.2-2        
    requests:        2.14.2-py36_0
    setuptools:      27.2.0-py36_0
    six:             1.10.0-py36_0
    sqlite:          3.13.0-0     
    tk:              8.5.18-0     
    toolz:           0.8.2-py36_0 
    tornado:         4.5.1-py36_0 
    wheel:           0.29.0-py36_0
    xz:              5.2.2-1
    yaml:            0.1.6-0
    zlib:            1.2.8-3
```

**Comment by mrocklin** [comment]
See discussion in https://github.com/dask/distributed/issues/962

If optional dependencies are no truely a thing then that sounds like a nice solution.  Otherwise we can make a `dask-core` package and a dask metapackage that includes dask-core and the extra dependencies or convenience.

@rth do you have any interest in tracking down in optional dependencies are now a reasonable thing for all conda-forge packages to start doing or, barring that, creating a dask-core feedstock on conda-forge?

**Comment by rth** [comment]
@jakirkham What is your opinion regarding specifying optional dependencies via `run_constrained`  on conda forge now or in the near future? The only relevant occurrence I found is [here](https://github.com/conda-forge/libcxx-feedstock/pull/4#issuecomment-315648265), and beyond listing optional dependencies in a separate section, it looks like there still isn't a way of installing them from command line https://github.com/conda/conda/issues/1696#issuecomment-300342745 Unless I missed something?

@mrocklin In any case, I would be happy to help in tracking the list of dependencies (and creating a dask-core feedstock, if necessary) depending on the solution that is chosen...

**Comment by mrocklin** [comment]
See https://github.com/conda-forge/staged-recipes/pull/3820 for dask-core feedstock

**Comment by rth** [comment]
@mrocklin Great, thank you! Closing as fixed.

**Comment by jakirkham** [comment]
> What is your opinion regarding specifying optional dependencies via `run_constrained`  on conda forge now or in the near future?

So `run_constrained` only really makes sense for situations where there is an optional dependency that must meet certain version constraints to work. I don't think it applies to this situation (though could be wrong).

Having `dask-core` capture the minimal requirements seems like a fine solution.

**Comment by jakirkham** [comment]
So should `dask` now become some sort of metapackage that depends on `python` at build and `dask-core` at runtime (in addition to other requirements)?

**Comment by jakirkham** [comment]
cc @jni

**Comment by mrocklin** [comment]
Yes, I think so.  I think that it should depend on dask-core, distributed, bokeh, and anything else that a decent fraction of users often expect to have when installing Dask

**Comment by mrocklin** [comment]
@jakirkham can you recommend a good example of a metapackage that I can use as a model for dask?

**Comment by jakirkham** [comment]
There are not lots of metapackages to look at. Though [this one]( https://github.com/conda-forge/cyclus-build-deps-feedstock/blob/master/recipe/meta.yaml ) might serve as a good example. Would ignore the `blas` stuff as that is not relevant here.
