### ISSUE TITLE
Removing pyarrow from the hard dependency?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/dask-feedstock#225]
### Comment:

I have to admit that I've somewhat lost track of the growth this feedstock (since https://github.com/conda-forge/dask-feedstock/issues/46) and I'm looking for guidance in better managing the dask dependency we have.

Generally, we do not need the features afforded by pyarrow. in https://github.com/conda-forge/dask-feedstock/pull/218 it seems that `pyarrow` was added adding difficult to resolve dependencies with `libaseil` through `libarrow`.

Personally, I feel like an `abseil` dependency makes the package quite "heavy". For example, today, the latest `dask` packages cannot be co-installed with `tensorflow` (we have had challenges moving toward the new abseil)

Is the recommendation for users that need minimal dask features to depend on `dask-core`? Should we work to move packages toward `dask-core`?

One "simple" solution for me would be to have a pinned issue with the general recommendations for working with dask vs dask-core.

**Comment by jakirkham** [comment]
Yeah `dask-core` is probably a better choice. This became more usable with the addition of some dependencies to `dask-core` in PR ( https://github.com/conda-forge/dask-core-feedstock/pull/93 )

It might make sense to add optional constraints to `dask-core` ( https://github.com/conda-forge/dask-core-feedstock/pull/171 ) to ease adding those optional dependencies (while guaranteeing version constraints are satisfied). If that were done, we could also drop the version constraints from `dask` ( https://github.com/conda-forge/dask-feedstock/pull/226 ). Perhaps this improves the utility of `dask-core` in these other use cases?

**Comment by jakirkham** [comment]
cc @jrbourbeau

**Comment by hmaarrfk** [comment]
dask-core it is !
