### ISSUE TITLE
Failure to upload package

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/dask-feedstock#240]
On `main` we're getting

```
ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
```

and aren't able to upload the 2023.9.3 release (see [this CI build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=792605&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&s=96ac2280-8cb4-5df5-99de-dd2da759617d) for the full traceback)

@conda-forge/core does anyone know what might be going on here? Is this happening elsewhere, or isolated to `dask`?

**Comment by hmaarrfk** [comment]
I tried to restart the azure builds. lets see what happens

**Comment by jrbourbeau** [comment]
Thanks @hmaarrfk! CI is green after a few restarts
