### ISSUE TITLE
Dask from conda-forge is empty

### ISSUE THREAD

**Issue by Juanlu001** [conda-forge/dask-feedstock#27]
https://anaconda.org/conda-forge/dask/0.15.2/download/linux-64/dask-0.15.2-py36_0.tar.bz2 it only has the info directory! I wonder what happened here...

**Comment by martindurant** [comment]
Dask is now a meta-package, depending on dask-core (which contains the files you were expecting) and distributed. You can view this package as "dask[complete]" in the pip sense.

**Comment by jakirkham** [comment]
As @martindurant has already said, this is expected and a natural consequence of `dask` now being a metapackage. If you have more questions, feel free to ask. Though am going to close this issue.

**Comment by Juanlu001** [comment]
I apologize for the silly issue :pray: I had an strange import error, went there and thought something was wrong on your side. After uninstalling and installing again everything works, should have checked three times. Thanks for your quick response!

**Comment by jakirkham** [comment]
Not silly at all.

It's possible something got weird in the upgrade. Had a similar experience in one of my environments where `distributed` lagged behind `dask` not that long ago. Caused some strange issues that upgrading fixed.

Glad to hear things are back up and working.

**Comment by martindurant** [comment]
Is it possible that `dask-core` installs files in site-packages/dask, and subsequent update of `dask` (this package) removes them?
