### ISSUE TITLE
Finer grained dependencies? (again)

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/dask-feedstock#46]
Would you accept a PR suggesting to create finer grained dependencies for dask using a single meta.yaml and the outputs section?

I have a good sample here (using split packages), but I don't know if it falls in line with your vision for distributing your package
* [recipe with comments](https://github.com/hmaarrfk/dask-feedstock/blob/split-packages/recipe/meta.yaml)
* [recipe without comments](https://github.com/hmaarrfk/dask-feedstock/blob/split-packages-no-comments/recipe/meta.yaml) Number of lines: 138

It is a few more lines of code than the current two recipes (57 + 46 = 103), but I think it keeps things in one place a little better vs having two recipe repos to maintain.

Thanks for considering again.

Related to: https://github.com/conda-forge/dask-feedstock/issues/22

Edit: specify that the samples provided use split packages.

**Comment by mrocklin** [comment]
Checking in.  Is there a reason to close this issue?  

FWIW I wouldn't treat silence on an issue as refusal, just a symptom of not having enough maintenance bandwidth.  I think it's ok to keep these sort of things open.

**Comment by hmaarrfk** [comment]
i am trying to find the most appropriate place to have this discussion. It
seems to be something people care about, in conda-forge as a whole, but
having a few of these issues sprinkled around GitHub doesn’t seem to be the
most effective way to have this discussion.

**Comment by jakirkham** [comment]
Not sure where the right place is for the discussion. Partially because it's not clear (at least to me) what these problems share in common except a desire to get more minimal packages. My way of saying let's figure out the use cases first.

One thing that I had mentioned to @jcrist and possibly also @mrocklin was turning this into a split package. That way there could be `dask-array`, `dask-dataframe`, etc. that would capture the optional dependencies in somewhat smaller versions, but be convenient for users to depend on.

It's also worth noting that `dask-core` has the code with basically no dependencies beyond `python`.

**Comment by hmaarrfk** [comment]
@jakirkham thank you for brining this up again.

The challenge I face is that when trying to use xarray and dask, dependencies totally ballooned up on my system and make it really slow at installing on new computers (which I seem to do alot....). This is understandable as both those projects can do really cool things, but often I only want a small subset.

the `dask-core` package that I define in the example doesn't have any hard dependencies, just `run_constrained` which was a design choice I made. The other outputs define unconstrained dependencies that get resolved to the necessary version by the `run_constrained` directive in `-core`. 
This can totally be changed around, but I think it would depend on how `dask.array` imports numpy. if it assumes the version of numpy when found is a supported version, or if it explicitly checks for `__version__`.

I feel like dask is a particularly easy project to start with split packages since:
1. You are all already maintaining a separate `-core` repository. 
2. It has no compile time dependencies making the recipe much simpler.

I don't think any users will be using the packages `dask-dataframe` when starting off with `dask`, but they will eventually transition to them once they have identified the features of dask that they need. At least, that is what I did.

**Comment by shoyer** [comment]
@hmaarrfk  If I understand your proposal correctly, the base `dask` package would become equivalent to the current `dask-core`? This seems pretty reasonable to me.

My main question would be how a dependent packages like xarray should handle it's own `run_constrained` directive. I suppose xarray would add the new `dask` to its own `run_constrained`, and then `xarray-all` would depend upon `dask-all`?

**Comment by shoyer** [comment]
> After having a few conversations and reading back on some old posts, (especially xarray's discussion), it seems that people like that dask and xarray are full fledged. This seems to have been an intentional design choice of conda-forge (and maybe conda).

Personally, I think this is probably a mistake, but I don't use conda for my day-to-day work, so I don't really care.

**Comment by hmaarrfk** [comment]
Honestly, I made `dask` a dummy package so that the decision to change from `dask-all` to `dask-core` would be a one liner.

What I'm more interested in personally is the ability to depend on `dask-array` without asking you all to create 5 feedstocks.

**Comment by shoyer** [comment]
> What I'm more interested in personally is the ability to depend on dask-array without asking you all to create 5 feedstocks.

This does seem like a win :)

**Comment by jakirkham** [comment]
Hence the split package suggestion ;)
