### ISSUE TITLE
packages with incorrect version constraints

### ISSUE THREAD

**Issue by grlee77** [conda-forge/dask-feedstock#81]
@jakirkham: As requested, I have moved this discussion here from dask/dask#4846

> Also would you be able to identify the ones with incorrect version constraints? That way we can hopefully get these in one pass.

The only two cases I encountered were for `win-32` and `win-64` in some Python 2.7 CI test runs for pyFFTW.  Dask gets installed alongside a NumPy version older than the minimum supported version (I think 1.2.2 requires >=1.13).

```
dask-1.2.2                 |             py_0          11 KB
dask-core-1.2.2            |             py_0         539 KB
```
were installed alongside:
```
numpy-1.11.3               |  py27hc42714f_10          11 KB
```

There could potentially be other versions with broken constraints, but I am not sure of any easy way to test for that.

Issue:

**Environment**:

The CI logs for those cases:
https://ci.appveyor.com/project/hgomersall/pyfftw/builds/26051197/job/1hj2bf2mnc59jagd#L155
https://ci.appveyor.com/project/hgomersall/pyfftw/builds/26051197/job/l5765hlr9342dv25#L152

**Comment by grlee77** [comment]
Checking the dask repo it looks like the dask 1.2.0 had a NumPy 1.11 dependency while dask 1.2.1 bumped it to 1.13. 

If I try creating a new conda environment on linux, things seem to work as expected:
```conda create -n np11 numpy=1.11 python=2.7 dask```
This results in numpy 1.11.3 with dask 1.2.0 (newest version still supporting NumPy 1.11.3)

I suspect the windows dask 1.2.1 might also have the same broken constraints as seen for 1.2.2 in the log above, but cannot test that at the moment.

**Comment by hmaarrfk** [comment]
given then is from 2019, lets close this.
